# Generated by Django 5.0.1 on 2024-02-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='product',
            new_name='cart',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='email',
            field=models.EmailField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
