# Generated by Django 5.0.1 on 2024-02-14 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_rename_product_orderplaced_cart_orderplaced_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cart'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
